### PR TITLE
toogle_switch with disabled states

### PR DESCRIPTION
**Pull request by rohitbhoite**
Added basic toggle disable functionality.
Toggle button states can be passed in states array just like labels/icons. If the value is false toggle button will be disabled
```
[
 ToggleSwitch(
              initialLabelIndex: 2,
              totalSwitches: 3,
              labels: ['America', 'Canada', 'Mexico'],
              states: [false,true,true],
              onToggle: (index) {
                print('switched to: $index');
              },
            ),]
```

### CODE REVIEW

**Comment by PramodJoshi** [comment]
@rohitbhoite Thanks for the PR! Great work!

**Comment by ArikSetyawan** [comment]
@PramodJoshi when this feature released?

**Comment by PramodJoshi** [comment]
@ArikSetyawan I'll try to get this as soon as I get a chance.

**Comment by PramodJoshi** [comment]
@ArikSetyawan apologies for the delay. This is now available in `toggle_switch: ^2.2.1`.

**Pull request merged**
