### PR TITLE
0.1.5:

### PR DESCRIPTION
**Pull request by rmanenti**
Changelog:

  Added support for disabling the Widget or one or more options it may contain;
   Added support to determine the colors for the background, text and divider when the widget or its children are disabled.

### CODE REVIEW

**Comment by rmanenti** [comment]
Hello there!
 
   First of all, thanks for creationg this great Widget. The only thing I missed about it is the option to entirely disable it or one of more of its options. I've implemented this feature. Please, check if it is ok to add it to the master branch.

Thank you!

**Comment by PramodJoshi** [comment]
@rmanenti Hi, thank you for submitting this pull request but it may not be a good fit for ToggleSwitch widget. Could you please briefly explain why disable feature adds value to this widget?

**Comment by rmanenti** [comment]
Pramod,

   Thanks for replying. The case scenario on which I have based this feature is when the ToggleSwitch widget can only be enabled if a previous input has value or has been selected. 

Something like this:

Date input > Load data > Enable Toggle Switch.

Thank you!

**Comment by PramodJoshi** [comment]
Hi Ricardo,

I think this is a good feature. Few things,
- I have added some new changes/features. Could you please pull the latest and re-PR?
- Please only commit `lib/toggle_switch.dart` and `example/lib/main.dart` (optional). It'd be great if you can add a simple example completely demonstrating this feature in `example/lib/main.dart` in the same format as the existing ones.
- Please use the existing code format i.e. `Reformat Code with dartfmt` in Android Studio.

Thank you again for submitting this PR.

-Pramod

**Pull request closed without merging**
