### PR TITLE
Added new features.

### PR DESCRIPTION
**Pull request by bsutton**
Added option minHeight which when set to null will allow the widget
to find its natural size based on the font content.
Added option setIndex to allow an user of ToggleSwitch to set its 
index programatically.
Added bool return to onToggle so the toggle could be rejected.

### CODE REVIEW

**Comment by PramodJoshi** [comment]
@bsutton Hi, thank you for submitting this pull request. `minWidth` is not working correctly with this branch.

**Comment by bsutton** [comment]
Can you provide more detail on the problem.
My code doesn't touch minWidth so I'm not certain how this pr would affect it.

**Comment by PramodJoshi** [comment]
When I run example from your branch and increase `minWidth`, it displays `ToggleSwitch` with default width instead of the new width. Your PR comments out minWidth constraints which i believe is causing this issue. We need minWidth constraints.

**Comment by PramodJoshi** [comment]
Hi Brett, there has been a number of new changes since your PR. I think some of the features from your PR is neatly covered in [a04d62e](https://github.com/PramodJoshi/toggle_switch/pull/8/commits/a04d62e3c0630785ad2b9dd66b2226a68bed57e2). Please pull the latest and re-PR if there are any features missing from your PR.

Thank you again for submitting this PR.

**Pull request closed without merging**
