### PR TITLE
Support border around selected active toggle.

### PR DESCRIPTION
**Pull request by itaishalom**

### CODE REVIEW

**Comment by itaishalom** [comment]
Dude you get to be more cooperative

**Comment by PramodJoshi** [comment]
"Dude", FYI, this is something I do part-time and I have been super busy lately with personal stuff as well as my full-time work stuff. I've tried my best to keep things in order with this project. Contacting me non-stop as soon as you submit a PR does not help and that def is not being "cooperative" from your side. I've always responded to your messages notifying you of my situation. Yet you still come here and post negative comments in PR. Please stop doing that.  I think it's only fair that you give me some time to work on the new changes. Again, I appreciate your contribution and thank you for your patience.

**Comment by itaishalom** [comment]
Thank you.

**Comment by itaishalom** [comment]
Sorry for the former message.
Waiting to check it on pub dev!

**Pull request merged**
